"""add_verification_score_and_face_path

Revision ID: 55d370d2a88e
Revises: b0752957f843
Create Date: 2026-04-10 22:17:28.054586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55d370d2a88e'
down_revision: Union[str, None] = 'b0752957f843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('face_image_path', sa.String(length=500), nullable=True))
    op.add_column('idv_applications', sa.Column('verification_score', sa.Float(), nullable=True))
    op.add_column('idv_applications', sa.Column('score_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idv_applications', 'score_details')
    op.drop_column('idv_applications', 'verification_score')
    op.drop_column('documents', 'face_image_path')
    # ### end Alembic commands ###
